language: node_js
env:
  global:
    - NODE_PATH=$PWD/src
    - GH_PERSONAL_TOKEN=dummy
    - GH_BASIC_CLIENT_ID=dummy
    - GH_BASIC_CLIENT_SECRET=dummy
before_install:
  - env | sort
  - npm install --global yarn
install:
  - make travis
  - echo 'America/New_York' | sudo tee /etc/timezone
node_js:
  - "node"
  - "lts/*"
script:
  - make test
