language: node_js
env:
  global:
    - NODE_PATH=$PWD/src
    - GH_PERSONAL_TOKEN=dummy
    - GH_BASIC_CLIENT_ID=dummy
    - GH_BASIC_CLIENT_SECRET=dummy
    - TZ=Canada/Eastern
before_install:
  - env | sort
  - npm install --global yarn
install:
  - make travis
node_js:
  - "node"
  - "lts/*"
script:
  - make test
